// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="sobel_sobel,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.648000,HLS_SYN_LAT=235367,HLS_SYN_TPT=none,HLS_SYN_MEM=3,HLS_SYN_DSP=0,HLS_SYN_FF=851,HLS_SYN_LUT=1658,HLS_VERSION=2022_2}" *)

module sobel (
        ap_clk,
        ap_rst_n,
        src_TDATA,
        src_TVALID,
        src_TREADY,
        src_TKEEP,
        src_TSTRB,
        src_TLAST,
        dst_TDATA,
        dst_TVALID,
        dst_TREADY,
        dst_TKEEP,
        dst_TSTRB,
        dst_TLAST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 5;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [7:0] src_TDATA;
input   src_TVALID;
output   src_TREADY;
input  [0:0] src_TKEEP;
input  [0:0] src_TSTRB;
input  [0:0] src_TLAST;
output  [7:0] dst_TDATA;
output   dst_TVALID;
input   dst_TREADY;
output  [0:0] dst_TKEEP;
output  [0:0] dst_TSTRB;
output  [0:0] dst_TLAST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [31:0] rows;
wire   [31:0] cols;
reg   [31:0] cols_read_reg_709;
reg   [31:0] rows_read_reg_716;
wire   [31:0] op2_assign_fu_463_p2;
reg   [31:0] op2_assign_reg_753;
wire    ap_CS_fsm_state4;
wire   [1:0] top_V_1_fu_522_p6;
reg   [1:0] top_V_1_reg_761;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln1027_fu_505_p2;
wire   [1:0] mid_V_1_fu_536_p6;
reg   [1:0] mid_V_1_reg_766;
wire   [1:0] btm_V_1_fu_550_p6;
reg   [1:0] btm_V_1_reg_771;
wire   [0:0] cmp_i_i120_fu_567_p2;
reg   [0:0] cmp_i_i120_reg_776;
wire   [0:0] cmp_i_i78_fu_572_p2;
reg   [0:0] cmp_i_i78_reg_781;
reg   [10:0] LineBuffer_address0;
reg    LineBuffer_ce0;
reg    LineBuffer_we0;
reg   [7:0] LineBuffer_d0;
reg    LineBuffer_ce1;
wire   [7:0] LineBuffer_q1;
reg   [10:0] LineBuffer_1_address0;
reg    LineBuffer_1_ce0;
reg    LineBuffer_1_we0;
reg   [7:0] LineBuffer_1_d0;
reg    LineBuffer_1_ce1;
wire   [7:0] LineBuffer_1_q1;
wire   [7:0] LineBuffer_2_q1;
wire    grp_sobel_Pipeline_1_fu_366_ap_start;
wire    grp_sobel_Pipeline_1_fu_366_ap_done;
wire    grp_sobel_Pipeline_1_fu_366_ap_idle;
wire    grp_sobel_Pipeline_1_fu_366_ap_ready;
wire   [7:0] grp_sobel_Pipeline_1_fu_366_WindowBuffer_5_out;
wire    grp_sobel_Pipeline_1_fu_366_WindowBuffer_5_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_1_fu_366_WindowBuffer_4_out;
wire    grp_sobel_Pipeline_1_fu_366_WindowBuffer_4_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_1_fu_366_WindowBuffer_3_out;
wire    grp_sobel_Pipeline_1_fu_366_WindowBuffer_3_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_1_fu_366_WindowBuffer_2_out;
wire    grp_sobel_Pipeline_1_fu_366_WindowBuffer_2_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_1_fu_366_WindowBuffer_1_out;
wire    grp_sobel_Pipeline_1_fu_366_WindowBuffer_1_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_1_fu_366_WindowBuffer_out;
wire    grp_sobel_Pipeline_1_fu_366_WindowBuffer_out_ap_vld;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_done;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_idle;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_ready;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_address0;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_ce0;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_we0;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_d0;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_address0;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_ce0;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_we0;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_d0;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_src_TREADY;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_keep_V_1_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_keep_V_1_out_ap_vld;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_strb_V_1_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_strb_V_1_out_ap_vld;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_done;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_idle;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_ready;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TDATA;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TREADY;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TKEEP;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TSTRB;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TLAST;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_src_TREADY;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_address0;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_ce0;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_we0;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_d0;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_address1;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_ce1;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_address0;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_ce0;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_we0;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_d0;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_address1;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_ce1;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_address0;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_ce0;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_we0;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_d0;
wire   [10:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_address1;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_ce1;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_33_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_33_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_35_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_35_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_31_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_31_out_ap_vld;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_34_out_o;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_34_out_o_ap_vld;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_30_out_o;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_30_out_o_ap_vld;
wire   [7:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_32_out_o;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_32_out_o_ap_vld;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_keep_V_3_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_keep_V_3_out_ap_vld;
wire   [0:0] grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_strb_V_3_out;
wire    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_strb_V_3_out_ap_vld;
reg   [0:0] data_p_keep_V_2_reg_178;
wire    ap_CS_fsm_state8;
reg   [0:0] data_p_strb_V_2_reg_188;
reg   [7:0] ap_phi_mux_WindowBuffer_14_phi_fu_201_p6;
reg   [7:0] ap_phi_mux_WindowBuffer_13_phi_fu_213_p6;
reg   [7:0] ap_phi_mux_WindowBuffer_12_phi_fu_225_p6;
reg   [7:0] ap_phi_mux_WindowBuffer_17_phi_fu_237_p6;
reg   [7:0] ap_phi_mux_WindowBuffer_16_phi_fu_252_p6;
reg   [7:0] ap_phi_mux_WindowBuffer_15_phi_fu_267_p6;
reg   [7:0] WindowBuffer_20_reg_279;
reg   [7:0] WindowBuffer_19_reg_292;
reg   [7:0] WindowBuffer_18_reg_305;
reg   [7:0] WindowBuffer_23_reg_318;
reg   [7:0] WindowBuffer_22_reg_334;
reg   [7:0] WindowBuffer_21_reg_350;
reg    grp_sobel_Pipeline_1_fu_366_ap_start_reg;
wire    ap_CS_fsm_state2;
reg   [7:0] WindowBuffer_5_fu_134;
wire    ap_CS_fsm_state3;
reg   [7:0] WindowBuffer_4_fu_130;
reg   [7:0] WindowBuffer_3_fu_126;
reg   [7:0] WindowBuffer_2_fu_122;
reg   [7:0] WindowBuffer_1_fu_118;
reg   [7:0] WindowBuffer_fu_114;
reg    grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start_reg;
reg    grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg   [0:0] data_p_keep_V_3_loc_fu_142;
reg   [0:0] data_p_strb_V_3_loc_fu_138;
reg   [1:0] btm_V_fu_94;
reg   [1:0] mid_V_fu_98;
reg   [1:0] top_V_fu_102;
reg   [1:0] lb_r_i_V_fu_106;
wire   [1:0] lb_r_i_V_2_fu_589_p3;
reg   [12:0] row_V_fu_110;
wire   [12:0] row_V_3_fu_597_p2;
wire   [31:0] zext_ln1027_fu_501_p1;
wire   [1:0] lb_r_i_V_1_fu_577_p2;
wire   [0:0] icmp_ln1019_fu_583_p2;
wire    ap_CS_fsm_state9;
wire    regslice_both_dst_V_data_V_U_apdone_blk;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_block_state3_on_subcall_done;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    regslice_both_src_V_data_V_U_apdone_blk;
wire   [7:0] src_TDATA_int_regslice;
wire    src_TVALID_int_regslice;
reg    src_TREADY_int_regslice;
wire    regslice_both_src_V_data_V_U_ack_in;
wire    regslice_both_src_V_keep_V_U_apdone_blk;
wire   [0:0] src_TKEEP_int_regslice;
wire    regslice_both_src_V_keep_V_U_vld_out;
wire    regslice_both_src_V_keep_V_U_ack_in;
wire    regslice_both_src_V_strb_V_U_apdone_blk;
wire   [0:0] src_TSTRB_int_regslice;
wire    regslice_both_src_V_strb_V_U_vld_out;
wire    regslice_both_src_V_strb_V_U_ack_in;
wire    regslice_both_src_V_last_V_U_apdone_blk;
wire   [0:0] src_TLAST_int_regslice;
wire    regslice_both_src_V_last_V_U_vld_out;
wire    regslice_both_src_V_last_V_U_ack_in;
wire    dst_TVALID_int_regslice;
wire    dst_TREADY_int_regslice;
wire    regslice_both_dst_V_data_V_U_vld_out;
wire    regslice_both_dst_V_keep_V_U_apdone_blk;
wire    regslice_both_dst_V_keep_V_U_ack_in_dummy;
wire    regslice_both_dst_V_keep_V_U_vld_out;
wire    regslice_both_dst_V_strb_V_U_apdone_blk;
wire    regslice_both_dst_V_strb_V_U_ack_in_dummy;
wire    regslice_both_dst_V_strb_V_U_vld_out;
wire    regslice_both_dst_V_last_V_U_apdone_blk;
wire    regslice_both_dst_V_last_V_U_ack_in_dummy;
wire    regslice_both_dst_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_sobel_Pipeline_1_fu_366_ap_start_reg = 1'b0;
#0 grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start_reg = 1'b0;
#0 grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start_reg = 1'b0;
end

sobel_LineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
LineBuffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(LineBuffer_address0),
    .ce0(LineBuffer_ce0),
    .we0(LineBuffer_we0),
    .d0(LineBuffer_d0),
    .address1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_address1),
    .ce1(LineBuffer_ce1),
    .q1(LineBuffer_q1)
);

sobel_LineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
LineBuffer_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(LineBuffer_1_address0),
    .ce0(LineBuffer_1_ce0),
    .we0(LineBuffer_1_we0),
    .d0(LineBuffer_1_d0),
    .address1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_address1),
    .ce1(LineBuffer_1_ce1),
    .q1(LineBuffer_1_q1)
);

sobel_LineBuffer_RAM_AUTO_1R1W #(
    .DataWidth( 8 ),
    .AddressRange( 1280 ),
    .AddressWidth( 11 ))
LineBuffer_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_address0),
    .ce0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_ce0),
    .we0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_we0),
    .d0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_d0),
    .address1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_address1),
    .ce1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_ce1),
    .q1(LineBuffer_2_q1)
);

sobel_sobel_Pipeline_1 grp_sobel_Pipeline_1_fu_366(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_Pipeline_1_fu_366_ap_start),
    .ap_done(grp_sobel_Pipeline_1_fu_366_ap_done),
    .ap_idle(grp_sobel_Pipeline_1_fu_366_ap_idle),
    .ap_ready(grp_sobel_Pipeline_1_fu_366_ap_ready),
    .WindowBuffer_5_out(grp_sobel_Pipeline_1_fu_366_WindowBuffer_5_out),
    .WindowBuffer_5_out_ap_vld(grp_sobel_Pipeline_1_fu_366_WindowBuffer_5_out_ap_vld),
    .WindowBuffer_4_out(grp_sobel_Pipeline_1_fu_366_WindowBuffer_4_out),
    .WindowBuffer_4_out_ap_vld(grp_sobel_Pipeline_1_fu_366_WindowBuffer_4_out_ap_vld),
    .WindowBuffer_3_out(grp_sobel_Pipeline_1_fu_366_WindowBuffer_3_out),
    .WindowBuffer_3_out_ap_vld(grp_sobel_Pipeline_1_fu_366_WindowBuffer_3_out_ap_vld),
    .WindowBuffer_2_out(grp_sobel_Pipeline_1_fu_366_WindowBuffer_2_out),
    .WindowBuffer_2_out_ap_vld(grp_sobel_Pipeline_1_fu_366_WindowBuffer_2_out_ap_vld),
    .WindowBuffer_1_out(grp_sobel_Pipeline_1_fu_366_WindowBuffer_1_out),
    .WindowBuffer_1_out_ap_vld(grp_sobel_Pipeline_1_fu_366_WindowBuffer_1_out_ap_vld),
    .WindowBuffer_out(grp_sobel_Pipeline_1_fu_366_WindowBuffer_out),
    .WindowBuffer_out_ap_vld(grp_sobel_Pipeline_1_fu_366_WindowBuffer_out_ap_vld)
);

sobel_sobel_Pipeline_VITIS_LOOP_84_1 grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start),
    .ap_done(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_done),
    .ap_idle(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_idle),
    .ap_ready(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_ready),
    .src_TVALID(src_TVALID_int_regslice),
    .cols(cols_read_reg_709),
    .LineBuffer_1_address0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_address0),
    .LineBuffer_1_ce0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_ce0),
    .LineBuffer_1_we0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_we0),
    .LineBuffer_1_d0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_d0),
    .LineBuffer_address0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_address0),
    .LineBuffer_ce0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_ce0),
    .LineBuffer_we0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_we0),
    .LineBuffer_d0(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_d0),
    .src_TDATA(src_TDATA_int_regslice),
    .src_TREADY(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_src_TREADY),
    .src_TKEEP(src_TKEEP_int_regslice),
    .src_TSTRB(src_TSTRB_int_regslice),
    .src_TLAST(src_TLAST_int_regslice),
    .data_p_keep_V_1_out(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_keep_V_1_out),
    .data_p_keep_V_1_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_keep_V_1_out_ap_vld),
    .data_p_strb_V_1_out(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_strb_V_1_out),
    .data_p_strb_V_1_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_strb_V_1_out_ap_vld)
);

sobel_sobel_Pipeline_VITIS_LOOP_114_3 grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start),
    .ap_done(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_done),
    .ap_idle(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_idle),
    .ap_ready(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_ready),
    .WindowBuffer_25(WindowBuffer_19_reg_292),
    .WindowBuffer_26(WindowBuffer_20_reg_279),
    .WindowBuffer_24(WindowBuffer_18_reg_305),
    .WindowBuffer_29(WindowBuffer_23_reg_318),
    .WindowBuffer_27(WindowBuffer_21_reg_350),
    .WindowBuffer_28(WindowBuffer_22_reg_334),
    .data_p_keep_V_2(data_p_keep_V_2_reg_178),
    .data_p_strb_V_2(data_p_strb_V_2_reg_188),
    .cols(cols_read_reg_709),
    .top_V_1(top_V_1_reg_761),
    .mid_V_1(mid_V_1_reg_766),
    .btm_V_1(btm_V_1_reg_771),
    .op2_assign(op2_assign_reg_753),
    .cmp_i_i78(cmp_i_i78_reg_781),
    .dst_TDATA(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TDATA),
    .dst_TVALID(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID),
    .dst_TREADY(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TREADY),
    .dst_TKEEP(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TKEEP),
    .dst_TSTRB(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TSTRB),
    .dst_TLAST(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TLAST),
    .src_TDATA(src_TDATA_int_regslice),
    .src_TVALID(src_TVALID_int_regslice),
    .src_TREADY(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_src_TREADY),
    .src_TKEEP(src_TKEEP_int_regslice),
    .src_TSTRB(src_TSTRB_int_regslice),
    .src_TLAST(src_TLAST_int_regslice),
    .LineBuffer_2_address0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_address0),
    .LineBuffer_2_ce0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_ce0),
    .LineBuffer_2_we0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_we0),
    .LineBuffer_2_d0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_d0),
    .LineBuffer_2_address1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_address1),
    .LineBuffer_2_ce1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_2_ce1),
    .LineBuffer_2_q1(LineBuffer_2_q1),
    .LineBuffer_1_address0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_address0),
    .LineBuffer_1_ce0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_ce0),
    .LineBuffer_1_we0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_we0),
    .LineBuffer_1_d0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_d0),
    .LineBuffer_1_address1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_address1),
    .LineBuffer_1_ce1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_ce1),
    .LineBuffer_1_q1(LineBuffer_1_q1),
    .LineBuffer_address0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_address0),
    .LineBuffer_ce0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_ce0),
    .LineBuffer_we0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_we0),
    .LineBuffer_d0(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_d0),
    .LineBuffer_address1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_address1),
    .LineBuffer_ce1(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_ce1),
    .LineBuffer_q1(LineBuffer_q1),
    .cmp_i_i120(cmp_i_i120_reg_776),
    .WindowBuffer_33_out(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_33_out),
    .WindowBuffer_33_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_33_out_ap_vld),
    .WindowBuffer_35_out(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_35_out),
    .WindowBuffer_35_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_35_out_ap_vld),
    .WindowBuffer_31_out(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_31_out),
    .WindowBuffer_31_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_31_out_ap_vld),
    .WindowBuffer_34_out_i(WindowBuffer_4_fu_130),
    .WindowBuffer_34_out_o(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_34_out_o),
    .WindowBuffer_34_out_o_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_34_out_o_ap_vld),
    .WindowBuffer_30_out_i(WindowBuffer_fu_114),
    .WindowBuffer_30_out_o(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_30_out_o),
    .WindowBuffer_30_out_o_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_30_out_o_ap_vld),
    .WindowBuffer_32_out_i(WindowBuffer_2_fu_122),
    .WindowBuffer_32_out_o(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_32_out_o),
    .WindowBuffer_32_out_o_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_32_out_o_ap_vld),
    .data_p_keep_V_3_out(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_keep_V_3_out),
    .data_p_keep_V_3_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_keep_V_3_out_ap_vld),
    .data_p_strb_V_3_out(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_strb_V_3_out),
    .data_p_strb_V_3_out_ap_vld(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_strb_V_3_out_ap_vld)
);

sobel_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .rows(rows),
    .cols(cols),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

sobel_mux_42_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 2 ),
    .din3_WIDTH( 2 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
mux_42_2_1_1_U54(
    .din0(2'd1),
    .din1(2'd2),
    .din2(2'd0),
    .din3(top_V_fu_102),
    .din4(lb_r_i_V_fu_106),
    .dout(top_V_1_fu_522_p6)
);

sobel_mux_42_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 2 ),
    .din3_WIDTH( 2 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
mux_42_2_1_1_U55(
    .din0(2'd2),
    .din1(2'd0),
    .din2(2'd1),
    .din3(mid_V_fu_98),
    .din4(lb_r_i_V_fu_106),
    .dout(mid_V_1_fu_536_p6)
);

sobel_mux_42_2_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 2 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 2 ),
    .din3_WIDTH( 2 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 2 ))
mux_42_2_1_1_U56(
    .din0(2'd0),
    .din1(2'd1),
    .din2(2'd2),
    .din3(btm_V_fu_94),
    .din4(lb_r_i_V_fu_106),
    .dout(btm_V_1_fu_550_p6)
);

sobel_regslice_both #(
    .DataWidth( 8 ))
regslice_both_src_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TDATA),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_data_V_U_ack_in),
    .data_out(src_TDATA_int_regslice),
    .vld_out(src_TVALID_int_regslice),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_data_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TKEEP),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_keep_V_U_ack_in),
    .data_out(src_TKEEP_int_regslice),
    .vld_out(regslice_both_src_V_keep_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_keep_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TSTRB),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_strb_V_U_ack_in),
    .data_out(src_TSTRB_int_regslice),
    .vld_out(regslice_both_src_V_strb_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_strb_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_src_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(src_TLAST),
    .vld_in(src_TVALID),
    .ack_in(regslice_both_src_V_last_V_U_ack_in),
    .data_out(src_TLAST_int_regslice),
    .vld_out(regslice_both_src_V_last_V_U_vld_out),
    .ack_out(src_TREADY_int_regslice),
    .apdone_blk(regslice_both_src_V_last_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 8 ))
regslice_both_dst_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TDATA),
    .vld_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID),
    .ack_in(dst_TREADY_int_regslice),
    .data_out(dst_TDATA),
    .vld_out(regslice_both_dst_V_data_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_data_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TKEEP),
    .vld_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID),
    .ack_in(regslice_both_dst_V_keep_V_U_ack_in_dummy),
    .data_out(dst_TKEEP),
    .vld_out(regslice_both_dst_V_keep_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_keep_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TSTRB),
    .vld_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID),
    .ack_in(regslice_both_dst_V_strb_V_U_ack_in_dummy),
    .data_out(dst_TSTRB),
    .vld_out(regslice_both_dst_V_strb_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_strb_V_U_apdone_blk)
);

sobel_regslice_both #(
    .DataWidth( 1 ))
regslice_both_dst_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TLAST),
    .vld_in(grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID),
    .ack_in(regslice_both_dst_V_last_V_U_ack_in_dummy),
    .data_out(dst_TLAST),
    .vld_out(regslice_both_dst_V_last_V_U_vld_out),
    .ack_out(dst_TREADY),
    .apdone_blk(regslice_both_dst_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_Pipeline_1_fu_366_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sobel_Pipeline_1_fu_366_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_Pipeline_1_fu_366_ap_ready == 1'b1)) begin
            grp_sobel_Pipeline_1_fu_366_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_ready == 1'b1)) begin
            grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start_reg <= 1'b1;
        end else if ((grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_ready == 1'b1)) begin
            grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        WindowBuffer_18_reg_305 <= 8'd0;
    end else if ((((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd1) & (1'b1 == ap_CS_fsm_state5)) | (~(top_V_1_fu_522_p6 == 2'd1) & ~(top_V_1_fu_522_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        WindowBuffer_18_reg_305 <= WindowBuffer_1_fu_118;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        WindowBuffer_19_reg_292 <= 8'd0;
    end else if ((((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd0) & (1'b1 == ap_CS_fsm_state5)) | (~(top_V_1_fu_522_p6 == 2'd1) & ~(top_V_1_fu_522_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        WindowBuffer_19_reg_292 <= WindowBuffer_3_fu_126;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_31_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        WindowBuffer_1_fu_118 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_31_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_sobel_Pipeline_1_fu_366_WindowBuffer_1_out_ap_vld == 1'b1))) begin
        WindowBuffer_1_fu_118 <= grp_sobel_Pipeline_1_fu_366_WindowBuffer_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        WindowBuffer_20_reg_279 <= WindowBuffer_5_fu_134;
    end else if ((~(top_V_1_fu_522_p6 == 2'd1) & ~(top_V_1_fu_522_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        WindowBuffer_20_reg_279 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((~(btm_V_1_fu_550_p6 == 2'd1) & ~(btm_V_1_fu_550_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((btm_V_1_fu_550_p6 == 2'd1) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        WindowBuffer_21_reg_350 <= ap_phi_mux_WindowBuffer_15_phi_fu_267_p6;
    end else if (((btm_V_1_fu_550_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        WindowBuffer_21_reg_350 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((btm_V_1_fu_550_p6 == 2'd1) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        WindowBuffer_22_reg_334 <= 8'd0;
    end else if (((~(btm_V_1_fu_550_p6 == 2'd1) & ~(btm_V_1_fu_550_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((btm_V_1_fu_550_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        WindowBuffer_22_reg_334 <= ap_phi_mux_WindowBuffer_16_phi_fu_252_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((~(btm_V_1_fu_550_p6 == 2'd1) & ~(btm_V_1_fu_550_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        WindowBuffer_23_reg_318 <= 8'd0;
    end else if ((((btm_V_1_fu_550_p6 == 2'd1) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((btm_V_1_fu_550_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        WindowBuffer_23_reg_318 <= ap_phi_mux_WindowBuffer_17_phi_fu_237_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_32_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        WindowBuffer_2_fu_122 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_32_out_o;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_sobel_Pipeline_1_fu_366_WindowBuffer_2_out_ap_vld == 1'b1))) begin
        WindowBuffer_2_fu_122 <= grp_sobel_Pipeline_1_fu_366_WindowBuffer_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_33_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        WindowBuffer_3_fu_126 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_33_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_sobel_Pipeline_1_fu_366_WindowBuffer_3_out_ap_vld == 1'b1))) begin
        WindowBuffer_3_fu_126 <= grp_sobel_Pipeline_1_fu_366_WindowBuffer_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_34_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        WindowBuffer_4_fu_130 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_34_out_o;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_sobel_Pipeline_1_fu_366_WindowBuffer_4_out_ap_vld == 1'b1))) begin
        WindowBuffer_4_fu_130 <= grp_sobel_Pipeline_1_fu_366_WindowBuffer_4_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_35_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        WindowBuffer_5_fu_134 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_35_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_sobel_Pipeline_1_fu_366_WindowBuffer_5_out_ap_vld == 1'b1))) begin
        WindowBuffer_5_fu_134 <= grp_sobel_Pipeline_1_fu_366_WindowBuffer_5_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_30_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        WindowBuffer_fu_114 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_WindowBuffer_30_out_o;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_sobel_Pipeline_1_fu_366_WindowBuffer_out_ap_vld == 1'b1))) begin
        WindowBuffer_fu_114 <= grp_sobel_Pipeline_1_fu_366_WindowBuffer_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        data_p_keep_V_2_reg_178 <= data_p_keep_V_3_loc_fu_142;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_p_keep_V_2_reg_178 <= grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_keep_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        data_p_strb_V_2_reg_188 <= data_p_strb_V_3_loc_fu_138;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        data_p_strb_V_2_reg_188 <= grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_data_p_strb_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        lb_r_i_V_fu_106 <= 2'd2;
    end else if (((icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        lb_r_i_V_fu_106 <= lb_r_i_V_2_fu_589_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_V_fu_110 <= 13'd1;
    end else if (((icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        row_V_fu_110 <= row_V_3_fu_597_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        btm_V_1_reg_771 <= btm_V_1_fu_550_p6;
        btm_V_fu_94 <= btm_V_1_fu_550_p6;
        cmp_i_i120_reg_776 <= cmp_i_i120_fu_567_p2;
        cmp_i_i78_reg_781 <= cmp_i_i78_fu_572_p2;
        mid_V_1_reg_766 <= mid_V_1_fu_536_p6;
        mid_V_fu_98 <= mid_V_1_fu_536_p6;
        top_V_1_reg_761 <= top_V_1_fu_522_p6;
        top_V_fu_102 <= top_V_1_fu_522_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        cols_read_reg_709 <= cols;
        rows_read_reg_716 <= rows;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_keep_V_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        data_p_keep_V_3_loc_fu_142 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_keep_V_3_out;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_strb_V_3_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        data_p_strb_V_3_loc_fu_138 <= grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_data_p_strb_V_3_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        op2_assign_reg_753 <= op2_assign_fu_463_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_1_address0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_1_address0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_address0;
    end else begin
        LineBuffer_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_1_ce0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_1_ce0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_ce0;
    end else begin
        LineBuffer_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_1_ce1 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_ce1;
    end else begin
        LineBuffer_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_1_d0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_1_d0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_d0;
    end else begin
        LineBuffer_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_1_we0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_1_we0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_1_we0;
    end else begin
        LineBuffer_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_address0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_address0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_address0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_address0;
    end else begin
        LineBuffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_ce0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_ce0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_ce0;
    end else begin
        LineBuffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_ce1 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_ce1;
    end else begin
        LineBuffer_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_d0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_d0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_d0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_d0;
    end else begin
        LineBuffer_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        LineBuffer_we0 = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_LineBuffer_we0;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        LineBuffer_we0 = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_LineBuffer_we0;
    end else begin
        LineBuffer_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state3_on_subcall_done)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((regslice_both_dst_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_dst_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd1) & (1'b1 == ap_CS_fsm_state5)) | (~(top_V_1_fu_522_p6 == 2'd1) & ~(top_V_1_fu_522_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_WindowBuffer_12_phi_fu_225_p6 = WindowBuffer_fu_114;
    end else if (((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_WindowBuffer_12_phi_fu_225_p6 = 8'd0;
    end else begin
        ap_phi_mux_WindowBuffer_12_phi_fu_225_p6 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_WindowBuffer_13_phi_fu_213_p6 = 8'd0;
    end else if ((((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd0) & (1'b1 == ap_CS_fsm_state5)) | (~(top_V_1_fu_522_p6 == 2'd1) & ~(top_V_1_fu_522_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_WindowBuffer_13_phi_fu_213_p6 = WindowBuffer_2_fu_122;
    end else begin
        ap_phi_mux_WindowBuffer_13_phi_fu_213_p6 = 'bx;
    end
end

always @ (*) begin
    if ((~(top_V_1_fu_522_p6 == 2'd1) & ~(top_V_1_fu_522_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_WindowBuffer_14_phi_fu_201_p6 = 8'd0;
    end else if ((((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd1) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln1027_fu_505_p2 == 1'd0) & (top_V_1_fu_522_p6 == 2'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_WindowBuffer_14_phi_fu_201_p6 = WindowBuffer_4_fu_130;
    end else begin
        ap_phi_mux_WindowBuffer_14_phi_fu_201_p6 = 'bx;
    end
end

always @ (*) begin
    if (((~(mid_V_1_fu_536_p6 == 2'd1) & ~(mid_V_1_fu_536_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((mid_V_1_fu_536_p6 == 2'd1) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_WindowBuffer_15_phi_fu_267_p6 = ap_phi_mux_WindowBuffer_12_phi_fu_225_p6;
    end else if (((mid_V_1_fu_536_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_WindowBuffer_15_phi_fu_267_p6 = 8'd0;
    end else begin
        ap_phi_mux_WindowBuffer_15_phi_fu_267_p6 = 'bx;
    end
end

always @ (*) begin
    if (((mid_V_1_fu_536_p6 == 2'd1) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_WindowBuffer_16_phi_fu_252_p6 = 8'd0;
    end else if (((~(mid_V_1_fu_536_p6 == 2'd1) & ~(mid_V_1_fu_536_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((mid_V_1_fu_536_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_WindowBuffer_16_phi_fu_252_p6 = ap_phi_mux_WindowBuffer_13_phi_fu_213_p6;
    end else begin
        ap_phi_mux_WindowBuffer_16_phi_fu_252_p6 = 'bx;
    end
end

always @ (*) begin
    if ((~(mid_V_1_fu_536_p6 == 2'd1) & ~(mid_V_1_fu_536_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_phi_mux_WindowBuffer_17_phi_fu_237_p6 = 8'd0;
    end else if ((((mid_V_1_fu_536_p6 == 2'd1) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((mid_V_1_fu_536_p6 == 2'd0) & (icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)))) begin
        ap_phi_mux_WindowBuffer_17_phi_fu_237_p6 = ap_phi_mux_WindowBuffer_14_phi_fu_201_p6;
    end else begin
        ap_phi_mux_WindowBuffer_17_phi_fu_237_p6 = 'bx;
    end
end

always @ (*) begin
    if (((regslice_both_dst_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        src_TREADY_int_regslice = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_src_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        src_TREADY_int_regslice = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_src_TREADY;
    end else begin
        src_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b0 == ap_block_state3_on_subcall_done) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln1027_fu_505_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state9 : begin
            if (((regslice_both_dst_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state3_on_subcall_done = ((grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_done == 1'b0) | (grp_sobel_Pipeline_1_fu_366_ap_done == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign cmp_i_i120_fu_567_p2 = (($signed(zext_ln1027_fu_501_p1) < $signed(rows_read_reg_716)) ? 1'b1 : 1'b0);

assign cmp_i_i78_fu_572_p2 = ((zext_ln1027_fu_501_p1 == rows_read_reg_716) ? 1'b1 : 1'b0);

assign dst_TVALID = regslice_both_dst_V_data_V_U_vld_out;

assign dst_TVALID_int_regslice = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TVALID;

assign grp_sobel_Pipeline_1_fu_366_ap_start = grp_sobel_Pipeline_1_fu_366_ap_start_reg;

assign grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start = grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_ap_start_reg;

assign grp_sobel_Pipeline_VITIS_LOOP_114_3_fu_393_dst_TREADY = (dst_TREADY_int_regslice & ap_CS_fsm_state7);

assign grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start = grp_sobel_Pipeline_VITIS_LOOP_84_1_fu_376_ap_start_reg;

assign icmp_ln1019_fu_583_p2 = ((lb_r_i_V_1_fu_577_p2 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_505_p2 = (($signed(zext_ln1027_fu_501_p1) > $signed(rows_read_reg_716)) ? 1'b1 : 1'b0);

assign lb_r_i_V_1_fu_577_p2 = (lb_r_i_V_fu_106 + 2'd1);

assign lb_r_i_V_2_fu_589_p3 = ((icmp_ln1019_fu_583_p2[0:0] == 1'b1) ? 2'd0 : lb_r_i_V_1_fu_577_p2);

assign op2_assign_fu_463_p2 = ($signed(cols_read_reg_709) + $signed(32'd4294967295));

assign row_V_3_fu_597_p2 = (row_V_fu_110 + 13'd1);

assign src_TREADY = regslice_both_src_V_data_V_U_ack_in;

assign zext_ln1027_fu_501_p1 = row_V_fu_110;


reg find_kernel_block = 0;
// synthesis translate_off
`include "sobel_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //sobel

