-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_sobel_Pipeline_VITIS_LOOP_84_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    src_TVALID : IN STD_LOGIC;
    cols : IN STD_LOGIC_VECTOR (31 downto 0);
    LineBuffer_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    LineBuffer_1_ce0 : OUT STD_LOGIC;
    LineBuffer_1_we0 : OUT STD_LOGIC;
    LineBuffer_1_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    LineBuffer_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    LineBuffer_ce0 : OUT STD_LOGIC;
    LineBuffer_we0 : OUT STD_LOGIC;
    LineBuffer_d0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    src_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    src_TREADY : OUT STD_LOGIC;
    src_TKEEP : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TSTRB : IN STD_LOGIC_VECTOR (0 downto 0);
    src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    data_p_keep_V_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    data_p_keep_V_1_out_ap_vld : OUT STD_LOGIC;
    data_p_strb_V_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    data_p_strb_V_1_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sobel_sobel_Pipeline_VITIS_LOOP_84_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_1 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000001";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln1027_fu_149_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal src_TDATA_blk_n : STD_LOGIC;
    signal zext_ln541_fu_161_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal data_p_strb_V_fu_66 : STD_LOGIC_VECTOR (0 downto 0);
    signal data_p_keep_V_fu_70 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_V_fu_74 : STD_LOGIC_VECTOR (12 downto 0);
    signal col_V_2_fu_155_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_col_V_1 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln1027_fu_145_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_147 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component sobel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    col_V_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_147)) then
                if ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1)) then 
                    col_V_fu_74 <= col_V_2_fu_155_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    col_V_fu_74 <= ap_const_lv13_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                data_p_keep_V_fu_70 <= src_TKEEP;
                data_p_strb_V_fu_66 <= src_TSTRB;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    LineBuffer_1_address0 <= zext_ln541_fu_161_p1(11 - 1 downto 0);

    LineBuffer_1_ce0_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            LineBuffer_1_ce0 <= ap_const_logic_1;
        else 
            LineBuffer_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LineBuffer_1_d0 <= src_TDATA;

    LineBuffer_1_we0_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            LineBuffer_1_we0 <= ap_const_logic_1;
        else 
            LineBuffer_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    LineBuffer_address0 <= zext_ln541_fu_161_p1(11 - 1 downto 0);

    LineBuffer_ce0_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            LineBuffer_ce0 <= ap_const_logic_1;
        else 
            LineBuffer_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    LineBuffer_d0 <= ap_const_lv8_0;

    LineBuffer_we0_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            LineBuffer_we0 <= ap_const_logic_1;
        else 
            LineBuffer_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)));
    end process;


    ap_condition_147_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
                ap_condition_147 <= (not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_col_V_1_assign_proc : process(ap_CS_fsm_state1, col_V_fu_74, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_col_V_1 <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_col_V_1 <= col_V_fu_74;
        end if; 
    end process;

    col_V_2_fu_155_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_col_V_1) + unsigned(ap_const_lv13_1));
    data_p_keep_V_1_out <= data_p_keep_V_fu_70;

    data_p_keep_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            data_p_keep_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            data_p_keep_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    data_p_strb_V_1_out <= data_p_strb_V_fu_66;

    data_p_strb_V_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            data_p_strb_V_1_out_ap_vld <= ap_const_logic_1;
        else 
            data_p_strb_V_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1027_fu_149_p2 <= "1" when (signed(zext_ln1027_fu_145_p1) < signed(cols)) else "0";

    src_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if (((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            src_TDATA_blk_n <= src_TVALID;
        else 
            src_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    src_TREADY_assign_proc : process(ap_CS_fsm_state1, src_TVALID, icmp_ln1027_fu_149_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (src_TVALID = ap_const_logic_0)))) and (icmp_ln1027_fu_149_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            src_TREADY <= ap_const_logic_1;
        else 
            src_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln1027_fu_145_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_V_1),32));
    zext_ln541_fu_161_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_col_V_1),64));
end behav;
