-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity sobel_sobel_Pipeline_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    WindowBuffer_5_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    WindowBuffer_5_out_ap_vld : OUT STD_LOGIC;
    WindowBuffer_4_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    WindowBuffer_4_out_ap_vld : OUT STD_LOGIC;
    WindowBuffer_3_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    WindowBuffer_3_out_ap_vld : OUT STD_LOGIC;
    WindowBuffer_2_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    WindowBuffer_2_out_ap_vld : OUT STD_LOGIC;
    WindowBuffer_1_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    WindowBuffer_1_out_ap_vld : OUT STD_LOGIC;
    WindowBuffer_out : OUT STD_LOGIC_VECTOR (7 downto 0);
    WindowBuffer_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of sobel_sobel_Pipeline_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv8_16 : STD_LOGIC_VECTOR (7 downto 0) := "00010110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal exitcond12_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_loop_init : STD_LOGIC;
    signal p_cast_fu_140_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal empty_21_fu_150_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal phi_urem_fu_50 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln77_fu_202_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_phi_urem_load : STD_LOGIC_VECTOR (3 downto 0);
    signal phi_mul_fu_54 : STD_LOGIC_VECTOR (7 downto 0);
    signal next_mul_fu_134_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_phi_mul_load : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_fu_58 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_20_fu_125_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_sig_allocacmp_p_load : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln77_fu_190_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln77_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component sobel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component sobel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    empty_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if ((exitcond12_fu_119_p2 = ap_const_lv1_0)) then 
                    empty_fu_58 <= empty_20_fu_125_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    empty_fu_58 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    phi_mul_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if ((exitcond12_fu_119_p2 = ap_const_lv1_0)) then 
                    phi_mul_fu_54 <= next_mul_fu_134_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_mul_fu_54 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    phi_urem_fu_50_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then
                if ((exitcond12_fu_119_p2 = ap_const_lv1_0)) then 
                    phi_urem_fu_50 <= select_ln77_fu_202_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    phi_urem_fu_50 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    WindowBuffer_1_out <= ap_const_lv8_0;

    WindowBuffer_1_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_loop_init, p_cast_fu_140_p4, empty_21_fu_150_p1, ap_start_int)
    begin
        if ((((empty_21_fu_150_p1 = ap_const_lv2_1) and (p_cast_fu_140_p4 = ap_const_lv2_0) and (exitcond12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            WindowBuffer_1_out_ap_vld <= ap_const_logic_1;
        else 
            WindowBuffer_1_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    WindowBuffer_2_out <= ap_const_lv8_0;

    WindowBuffer_2_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_loop_init, p_cast_fu_140_p4, empty_21_fu_150_p1, ap_start_int)
    begin
        if ((((empty_21_fu_150_p1 = ap_const_lv2_0) and (p_cast_fu_140_p4 = ap_const_lv2_1) and (exitcond12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            WindowBuffer_2_out_ap_vld <= ap_const_logic_1;
        else 
            WindowBuffer_2_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    WindowBuffer_3_out <= ap_const_lv8_0;

    WindowBuffer_3_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_loop_init, p_cast_fu_140_p4, empty_21_fu_150_p1, ap_start_int)
    begin
        if ((((empty_21_fu_150_p1 = ap_const_lv2_1) and (p_cast_fu_140_p4 = ap_const_lv2_1) and (exitcond12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            WindowBuffer_3_out_ap_vld <= ap_const_logic_1;
        else 
            WindowBuffer_3_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    WindowBuffer_4_out <= ap_const_lv8_0;

    WindowBuffer_4_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_loop_init, p_cast_fu_140_p4, empty_21_fu_150_p1, ap_start_int)
    begin
        if (((not((p_cast_fu_140_p4 = ap_const_lv2_1)) and not((p_cast_fu_140_p4 = ap_const_lv2_0)) and (empty_21_fu_150_p1 = ap_const_lv2_0) and (exitcond12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            WindowBuffer_4_out_ap_vld <= ap_const_logic_1;
        else 
            WindowBuffer_4_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    WindowBuffer_5_out <= ap_const_lv8_0;

    WindowBuffer_5_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_loop_init, p_cast_fu_140_p4, empty_21_fu_150_p1, ap_start_int)
    begin
        if (((not((p_cast_fu_140_p4 = ap_const_lv2_1)) and not((p_cast_fu_140_p4 = ap_const_lv2_0)) and (empty_21_fu_150_p1 = ap_const_lv2_1) and (exitcond12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            WindowBuffer_5_out_ap_vld <= ap_const_logic_1;
        else 
            WindowBuffer_5_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    WindowBuffer_out <= ap_const_lv8_0;

    WindowBuffer_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_loop_init, p_cast_fu_140_p4, empty_21_fu_150_p1, ap_start_int)
    begin
        if ((((empty_21_fu_150_p1 = ap_const_lv2_0) and (p_cast_fu_140_p4 = ap_const_lv2_0) and (exitcond12_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)) or ((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1)))) then 
            WindowBuffer_out_ap_vld <= ap_const_logic_1;
        else 
            WindowBuffer_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln77_fu_190_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_urem_load) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start_int)
    begin
        if ((ap_start_int = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, exitcond12_fu_119_p2, ap_start_int)
    begin
        if (((exitcond12_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_p_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, empty_fu_58)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_p_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_p_load <= empty_fu_58;
        end if; 
    end process;


    ap_sig_allocacmp_phi_mul_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, phi_mul_fu_54)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_phi_mul_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_phi_mul_load <= phi_mul_fu_54;
        end if; 
    end process;


    ap_sig_allocacmp_phi_urem_load_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, phi_urem_fu_50)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_phi_urem_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_phi_urem_load <= phi_urem_fu_50;
        end if; 
    end process;

    empty_20_fu_125_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_p_load) + unsigned(ap_const_lv4_1));
    empty_21_fu_150_p1 <= ap_sig_allocacmp_phi_urem_load(2 - 1 downto 0);
    exitcond12_fu_119_p2 <= "1" when (ap_sig_allocacmp_p_load = ap_const_lv4_9) else "0";
    icmp_ln77_fu_196_p2 <= "1" when (unsigned(add_ln77_fu_190_p2) < unsigned(ap_const_lv4_3)) else "0";
    next_mul_fu_134_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_phi_mul_load) + unsigned(ap_const_lv8_16));
    p_cast_fu_140_p4 <= ap_sig_allocacmp_phi_mul_load(7 downto 6);
    select_ln77_fu_202_p3 <= 
        add_ln77_fu_190_p2 when (icmp_ln77_fu_196_p2(0) = '1') else 
        ap_const_lv4_0;
end behav;
